#!/usr/bin/env python3
# Scans source for non-ASCII (Korean) characters actually used in UI/content
# strings and emits src/core/GlyphSet.h with a minimal glyph source string.
# Re-run after editing any user-facing Korean text.
import re, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCAN = [ROOT/"src", ROOT/"tools/gen_game.cpp", ROOT/"tools/gen_concept_maps.cpp"]

def files():
    for s in SCAN:
        if s.is_file(): yield s
        else:
            for ext in ("*.cpp","*.h"):
                yield from s.rglob(ext)

chars = set()
for f in files():
    if f.name == "GlyphSet.h":  # never feed the generated file back in
        continue
    try: txt = f.read_text(encoding="utf-8")
    except Exception: continue
    for ch in txt:
        o = ord(ch)
        if o > 0x7F:  # any non-ASCII glyph the UI may render
            chars.add(ch)

ordered = "".join(sorted(chars))
# C++ \u escapes keep the header pure-ASCII (portable across compilers/encodings).
esc = "".join("\\u%04x" % ord(c) for c in ordered)

out = ROOT/"src/core/GlyphSet.h"
out.write_text(
"#pragma once\n"
"// AUTO-GENERATED by tools/gen_glyphset.py — do not edit by hand.\n"
"// The minimal set of non-ASCII (Korean) glyphs used anywhere in the UI and\n"
"// sample game, so the font atlas bakes only what we actually draw.\n"
"namespace tsukuru {\n"
f"// {len(ordered)} unique non-ASCII glyphs\n"
f'inline const char* kUiGlyphs = "{esc}";\n'
"} // namespace tsukuru\n", encoding="utf-8")
print(f"GlyphSet.h: {len(ordered)} unique non-ASCII glyphs")
